- type: job
  id: Chemist
  name: job-name-chemist
  description: job-description-chemist
  playTimeTracker: JobChemist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 1800
  startingGear: ChemistGear
  setPreference: false
  icon: "Chemist"
  supervisors: job-supervisors-cmo
  antagAdvantage: 2 # Chem access
  access:
  - Medical
  - Chemistry
  extendedAccess:
  - Maintenance

- type: startingGear
  id: ChemistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChemistry
    back: ClothingBackpackChemistryFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatLabChem
    id: ChemistryPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedical
    pocket1: HandLabeler
    # the purple glasses?
  innerclothingskirt: ClothingUniformJumpskirtChemistry
  satchel: ClothingBackpackSatchelChemistryFilled
  duffelbag: ClothingBackpackDuffelChemistryFilled
