using Content.Shared.Borgs;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Borgs.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LawsMenu : DefaultWindow
    {
        [Dependency] private readonly IEntityManager _entityManager = default!;

        public LawsBoundUserInterface Owner { get; }

        public LawsMenu(LawsBoundUserInterface owner)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            Owner = owner;
            UpdateLaws();
        }

        public void UpdateLaws()
        {
            if (!_entityManager.TryGetComponent<LawsComponent>(Owner.Machine, out var laws))
                return;

            foreach (var law in laws.Laws)
            {
                Laws.AddItem(law);
            }
        }
    }
}
