using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.UserInterface.Screens;

[GenerateTypedNameReferences]
public sealed partial class SeparatedChatGameScreen : UIScreen
{
    public SeparatedChatGameScreen()
    {
        RobustXamlLoader.Load(this);

        AutoscaleMaxResolution = new Vector2i(1080, 770);

        SetAnchorPreset(ScreenContainer, LayoutPreset.Wide);
        SetAnchorPreset(ViewportContainer, LayoutPreset.Wide);
        SetAnchorPreset(MainViewport, LayoutPreset.Wide);
        SetAnchorAndMarginPreset(Actions, LayoutPreset.TopLeft, margin: 10);
        Alerts.AlertContainer.Orientation = BoxContainer.LayoutOrientation.Horizontal;
        ScreenContainer.SplitEdgeSeparation = 0;
        ScreenContainer.SplitWidth = 0;
        ViewportAndHUDContainer.SplitEdgeSeparation = 5;
        ViewportAndHUDContainer.SplitWidth = 5;
    }
}
