- type: entity
  id: EngineeringTechFabCircuitboard
  parent: BaseMachineCircuitboard
  name: engineering techfab machine board
  description: A machine printed circuit board for a engineering techfab
  components:
    - type: Sprite
      state: engineering
    - type: MachineBoard
      prototype: EngineeringTechFab
      requirements:
        MatterBin: 2
        Manipulator: 2
      tagRequirements:
        GlassBeaker:
          Amount: 2
          DefaultPrototype: Beaker
          ExamineName: Glass Beaker

- type: entity
  id: ServiceTechFabCircuitboard
  parent: BaseMachineCircuitboard
  name: service techfab machine board
  description: A machine printed circuit board for a service techfab
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: ServiceTechFab
      requirements:
        MatterBin: 2
        Manipulator: 2
      tagRequirements:
        GlassBeaker:
          Amount: 2
          DefaultPrototype: Beaker
          ExamineName: Glass Beaker

- type: entity
  id: ScienceTechFabCircuitboard
  parent: BaseMachineCircuitboard
  name: epistemics techfab machine board
  description: A machine printed circuit board for an epistemics techfab
  components:
    - type: Sprite
      state: science
    - type: MachineBoard
      prototype: ScienceTechFab
      requirements:
        MatterBin: 2
        Manipulator: 2
      tagRequirements:
        GlassBeaker:
          Amount: 2
          DefaultPrototype: Beaker
          ExamineName: Glass Beaker

- type: entity
  id: MetempsychoticMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: metempsychotic machine machine board
  description: A machine printed circuit board for a cloning pod
  components:
    - type: Sprite
      state: medical
    - type: MachineBoard
      prototype: MetempsychoticMachine
      requirements:
        ScanningModule: 2
        Manipulator: 2
      materialRequirements:
        Glass: 1
        Cable: 1
    - type: ReverseEngineering
      difficulty: 3
      recipes:
        - MetempsychoticMachineCircuitboard

- type: entity
  id: ReverseEngineeringMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: reverse engineering machine machine board
  description: A machine printed circuit board for a reverse engineering machine
  components:
    - type: Sprite
      state: engineering
    - type: MachineBoard
      prototype: ReverseEngineeringMachine
      requirements:
        ScanningModule: 1
        Manipulator: 1
      materialRequirements:
        Glass: 1
        Cable: 1
        Diamond: 10
      tagRequirements:
        BorgArm:
          Amount: 3
          DefaultPrototype: LeftArmBorg
          ExamineName: borg arm
    - type: ReverseEngineering
      difficulty: 3
      recipes:
        - ReverseEngineeringMachineCircuitboard
