using System;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.MachineLinking.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class SignalTimerWindow : DefaultWindow
    {
        private SignalTimerBoundUserInterface _bui;

        public event Action<float>? OnTimeEntered;

        public SignalTimerWindow(SignalTimerBoundUserInterface boundUserInterface)
        {
            _bui = boundUserInterface;

            RobustXamlLoader.Load(this);

            SecondsLabelEdit.OnTextEntered += HandleTextEntered;

            ButtonStart.OnPressed += _ => _bui.OnStart();
            CancelButton.OnPressed += _ => _bui.OnCancel();
        }

        private void HandleTextEntered(LineEdit.LineEditEventArgs e)
        {
            if (OnTimeEntered != null)
                if (float.TryParse(e.Text, out float length))
                    OnTimeEntered(length);
        }

        public void SetCurrentTime(string label)
        {
            SecondsLabelEdit.Text = label;
        }

        public void HandleState(bool TimerOn, float remaining)
        {
            StartBox.Visible = !TimerOn;
            EndBox.Visible = TimerOn;

            if (TimerOn)
            {
                TimeRemainingLabel.Text = (Loc.GetString("signal-timer-window-time-remaining", ("sec", (int) remaining)));
            }
        }
    }
}
