using System;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.MachineLinking.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class SignalTimerWindow : DefaultWindow
    {
        private SignalTimerBoundUserInterface _bui;

        public event Action<float>? OnTimeEntered;


        public SignalTimerWindow(SignalTimerBoundUserInterface boundUserInterface)
        {
            _bui = boundUserInterface;

            RobustXamlLoader.Load(this);

            SecondsLabelEdit.OnTextEntered += e => OnTimeEntered?.Invoke(float.Parse(e.Text));

            ButtonStart.OnPressed += _ => _bui.OnStart();
            ButtonStop.OnPressed += _ => _bui.OnStop();
        }

        public void SetCurrentStatus(string label)
        {
            StatusLabelEdit.Text = label;
        }

        public void SetCurrentTime(string label)
        {
            SecondsLabelEdit.Text = label;
        }
    }
}
