using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.MachineLinking.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class SignalTimerWindow : DefaultWindow
    {
        public event Action<string>? OnTimeEntered;

        public SignalTimerWindow()
        {
            RobustXamlLoader.Load(this);

            TimeLabelEdit.OnTextEntered += e => OnTimeEntered?.Invoke(e.Text);
        }

        public void SetCurrentStatus(string label)
        {
            StatusLabelEdit.Text = label;
        }

        public void SetCurrentTime(string label)
        {
            TimeLabelEdit.Text = label;
        }
    }
}
