using Content.Shared.Borgs;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.Borgs
{
    [GenerateTypedNameReferences]
    public sealed partial class LawsMenu : DefaultWindow
    {
        [Dependency] private readonly IEntityManager _entityManager = default!;
        public LawsBoundUserInterface Owner { get; }

        public LawsMenu(LawsBoundUserInterface owner)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            Owner = owner;
            UpdateLaws();

            if (_entityManager.TryGetComponent<LawsComponent>(owner.Machine, out var laws))
                StateLawsButton.Visible = laws.CanState;

            StateLawsButton.OnPressed += _ =>
            {
                StateLaws();
            };
        }

        /// why don't the style classes work?? i've tried a bunch of ways to get a BG working
        public void UpdateLaws()
        {
            if (!_entityManager.TryGetComponent<LawsComponent>(Owner.Machine, out var laws))
                return;

            Laws.DisposeAllChildren();

            foreach (var law in laws.Laws)
            {
                var lawLabel = new RichTextLabel(){
                StyleClasses = {StyleNano.StyleClassLabelKeyText}
                };
                lawLabel.SetMessage(law);
                Laws.AddChild(lawLabel);
            }
        }

        /// <summary>
        ///     Sends a message to state each of the laws in chat.
        /// </summary>
        private void StateLaws()
        {
            Owner.StateLawsMessage();
        }
    }
}
