contact_links:
  - name: Report a Security Exploit
    url: https://discord.gg/MwDDf6t
    about: Please report serious security exploits and vulnerabilities to @PJB3005. (PJB#3005/97089048065097728 on discord).
  - name: Request a Feature
    url: https://discord.gg/s7Er9mejpp
    about: Submit feature requests on our [discord server](https://discord.gg/s7Er9mejpp).
