- type: latheRecipe
  id: Handcuffs
  icon:
    sprite: Objects/Misc/handcuffs.rsi
    state: handcuff
  result: Handcuffs
  completetime: 2
  materials:
    Steel: 300

- type: latheRecipe
  id: Zipties
  icon:
    sprite: Objects/Misc/zipties.rsi
    state: cuff
  result: Zipties
  completetime: 2
  materials:
    Plastic: 200

- type: latheRecipe
  id: Stunbaton
  icon:
    sprite: Objects/Weapons/Melee/stunbaton.rsi
    state: stunbaton_off
  result: Stunbaton
  completetime: 2
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  id: ForensicPad
  icon:
    sprite: Objects/Misc/bureaucracy.rsi
    state: paper
  result: ForensicPad
  completetime: 4
  materials:
    Plastic: 100

- type: latheRecipe
  id: ClothingEyesGlassesSecurity
  icon:
    sprite: Clothing/Eyes/Glasses/secglasses.rsi
    state: icon
  result: ClothingEyesGlassesSecurity
  completetime: 2
  materials:
    Steel: 300
    Glass: 200

- type: latheRecipe
  id: RiotShield
  icon:
    sprite: Objects/Weapons/Melee/shields.rsi
    state: riot-icon
  result: RiotShield
  completetime: 4
  materials:
    Steel: 400
    Glass: 400

- type: latheRecipe
  id: Flash
  icon:
    sprite: Objects/Weapons/Melee/flash.rsi
    state: flash
  result: Flash
  completetime: 2
  materials:
    Glass: 100
    Plastic: 200
    Steel: 100

- type: latheRecipe
  id: ShellShotgunBeanbag
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/shotgun_shell.rsi
    state: beanbag
  result: ShellShotgunBeanbag
  completetime: 2
  materials:
    Plastic: 15
    Steel: 10

- type: latheRecipe
  id: CartridgePistolRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgePistolRubber
  completetime: 2
  materials:
    Plastic: 5
    Steel: 5

- type: latheRecipe
  id: CartridgeMagnumRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgeMagnumRubber
  completetime: 2
  materials:
    Plastic: 5
    Steel: 5

- type: latheRecipe
  id: CartridgeCaselessRifleRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgeCaselessRifleRubber
  completetime: 2
  materials:
    Plastic: 10
    Steel: 5

- type: latheRecipe
  id: CartridgeLightRifleRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgeLightRifleRubber
  completetime: 2
  materials:
    Plastic: 10
    Steel: 5

- type: latheRecipe
  id: CartridgeRifleRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgeRifleRubber
  completetime: 2
  materials:
    Plastic: 10
    Steel: 5

- type: latheRecipe
  id: CartridgePistol
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgePistol
  completetime: 2
  materials:
    Steel: 10

- type: latheRecipe
  id: ShellShotgun
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/shotgun_shell.rsi
    state: base
  result: ShellShotgun
  completetime: 2
  materials:
    Steel: 20

- type: latheRecipe
  id: CartridgeMagnum
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgeMagnum
  completetime: 2
  materials:
    Steel: 20

- type: latheRecipe
  id: CartridgeLightRifle
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgeLightRifle
  completetime: 2
  materials:
    Steel: 30

- type: latheRecipe
  id: ShellShotgunFlare
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/shotgun_shell.rsi
    state: flare
  result: ShellShotgunFlare
  completetime: 2
  materials:
    Plastic: 20
    Steel: 5

- type: latheRecipe
  id: ShellTranquilizer
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/shotgun_shell.rsi
    state: practice
  result: ShellTranquilizer
  completetime: 4
  materials:
    Plastic: 15
    Steel: 10
    Glass: 5

- type: latheRecipe
  id: TargetHuman
  icon:
    sprite: Objects/Specific/Security/target.rsi
    state: target_h
  result: TargetHuman
  completetime: 5
  materials:
    Steel: 10

- type: latheRecipe
  id: TargetClown
  icon:
    sprite: Objects/Specific/Security/target.rsi
    state: target_c
  result: TargetClown
  completetime: 5
  materials:
    Steel: 10

- type: latheRecipe
  id: TargetSyndicate
  icon:
    sprite: Objects/Specific/Security/target.rsi
    state: target_s
  result: TargetSyndicate
  completetime: 5
  materials:
    Steel: 10
