# Leader
- type: job
  id: ERTLeader
  name: job-name-ertleader
  description: job-description-ertleader
  playTimeTracker: JobERTLeader
  setPreference: false
  startingGear: ERTLeaderGear
  icon: "Nanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess

- type: startingGear
  id: ERTLeaderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeaderFilled
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHelmetHelmet
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorBlack
    outerclothing: ClothingOuterVestKevlar
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltERTLeader
    belt: ClothingBeltSecurityWebbing
    pocket1: Flare

- type: startingGear
  id: ERTLeaderGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeaderFilled
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskBreath
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterHardsuitERTLeader
    suitStorage: OxygenTankFilled
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltERTLeader
    belt: ClothingBeltSecurityFilled
    pocket1: Flare

# Engineer
- type: job
  id: ERTEngineer
  name: job-name-ertengineer
  description: job-description-ertengineer
  playTimeTracker: JobERTEngineer
  setPreference: false
  startingGear: ERTEngineerGear
  icon: "Nanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess

- type: startingGear
  id: ERTEngineerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineerFilled
    shoes: ClothingShoesBootsWork
    head: ClothingHeadHelmetHelmet
    eyes: ClothingEyesGlassesMeson
    gloves: ClothingHandsGlovesColorYellow
    outerClothing: ClothingOuterVestKevlar
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltERTEngineer
    belt: ClothingBeltUtilityFilled
    pocket1: Flare

- type: startingGear
  id: ERTEngineerGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineerFilled
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskBreath
    eyes: ClothingEyesGlassesMeson
    gloves: ClothingHandsGlovesColorYellow
    outerClothing: ClothingOuterHardsuitERTEngineer
    suitStorage: OxygenTankFilled
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltERTEngineer
    belt: ClothingBeltUtilityFilled
    pocket1: Flare

# Security
- type: job
  id: ERTSecurity
  name: job-name-ertsecurity
  description: job-description-ertsecurity
  playTimeTracker: JobERTSecurity
  setPreference: false
  startingGear: ERTSecurityGear
  icon: "Nanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess

- type: startingGear
  id: ERTSecurityGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurityFilled
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHelmetHelmet
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterVestKevlar
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltERTSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: Flare

- type: startingGear
  id: ERTSecurityGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurityFilled
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskBreath
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterHardsuitERTSecurity
    suitStorage: OxygenTankFilled
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltERTSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: Flare

# Medical
- type: job
  id: ERTMedical
  name: job-name-ertmedic
  description: job-description-ertmedic
  playTimeTracker: JobERTMedical
  setPreference: false
  startingGear: ERTMedicalGear
  icon: "Nanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess

- type: startingGear
  id: ERTMedicalGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedicalFilled
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHelmetHelmet
    eyes: ClothingEyesHudMedical
    gloves: ClothingHandsGlovesNitrile
    outerClothing: ClothingOuterVestKevlar
    id: ERTMedicalPDA
    ears: ClothingHeadsetAltERTMedic
    belt: ClothingBeltMedicalFilled
    pocket1: HandheldHealthAnalyzer
    pocket2: Flare

- type: startingGear
  id: ERTMedicalGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedicalFilled
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskBreath
    eyes: ClothingEyesHudMedical
    gloves: ClothingHandsGlovesNitrile
    outerClothing: ClothingOuterHardsuitERTMedical
    suitStorage: OxygenTankFilled
    id: ERTMedicalPDA
    ears: ClothingHeadsetAltERTMedic
    belt: ClothingBeltMedicalFilled
    pocket1: HandheldHealthAnalyzer
    pocket2: Flare

# Janitor
- type: job
  id: ERTJanitor
  name: job-name-ertjanitor
  description: job-description-ertjanitor
  playTimeTracker: JobERTJanitor
  setPreference: false
  startingGear: ERTJanitorGear
  icon: "Nanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess

- type: startingGear
  id: ERTJanitorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitorFilled
    shoes: ClothingShoesGaloshes
    head: ClothingHeadHelmetHelmet
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorYellowBudget
    outerClothing: ClothingOuterVestKevlar
    id: ERTLJanitorPDA
    ears: ClothingHeadsetAltERTJanitor
    belt: ClothingBeltJanitorFilled
    pocket1: SprayBottleSpaceCleaner
    pocket2: Flare

- type: startingGear
  id: ERTJanitorGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitorFilled
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskBreath
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorYellowBudget
    outerClothing: ClothingOuterHardsuitERTJanitor
    suitStorage: OxygenTankFilled
    id: ERTLJanitorPDA
    ears: ClothingHeadsetAltERTJanitor
    belt: ClothingBeltJanitorFilled
    pocket1: SprayBottleSpaceCleaner
    pocket2: Flare
