- type: job
  id: Psychologist
  name: job-name-psychologist
  description: job-description-psychologist
  playTimeTracker: JobPsychologist
  startingGear: PsychologistGear
  setPreference: false
  icon: "Psychologist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  extendedAccess:
  - Chemistry
  - Maintenance

- type: startingGear
  id: PsychologistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPsychologist
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesLeather
    id: PsychologistPDA
    ears: ClothingHeadsetMedical
  innerclothingskirt: ClothingUniformJumpsuitPsychologist
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
