using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.XAML;
using Content.Client.Nyanotrasen.UserInterface.CustomControls;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class GlimmerMonitorUiFragment : BoxContainer
{
    [Dependency] private readonly IResourceCache _resourceCache = default!;
    public GlimmerMonitorUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        UpdateState(0);
        var graph = new GlimmerGraph(_resourceCache, new List<int>{ 0, 20, 40, 40, 80, 150, 130, 210, 220, 270, 250, 310, 400, 420, 390, 500});
        graph.SetSize = (450, 250);
        MonitorBox.AddChild(graph);
    }

    public void UpdateState(int glimmer)
    {
        GlimmerLabel.Text = Loc.GetString("glimmer-monitor-current-glimmer", ("glimmer", glimmer));
    }
}
