using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class GlimmerMonitorUiFragment : BoxContainer
{
    public GlimmerMonitorUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        UpdateState(0);
    }

    public void UpdateState(int glimmer)
    {
        GlimmerLabel.Text = Loc.GetString("glimmer-monitor-current-glimmer", ("glimmer", glimmer));
    }
}
