- type: job
  id: CargoTechnician
  name: "cargo technician"
  setPreference: false
  startingGear: CargoTechGear
  departments:
  - Cargo
  icon: "CargoTechnician"
  supervisors: "the quartermaster and head of personnel"
  access:
  - Cargo
  - Maintenance
  - External

- type: startingGear
  id: CargoTechGear
  equipment:
    head: ClothingHeadHatCargosoft
    jumpsuit: ClothingUniformJumpsuitCargo
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: CargoPDA
    ears: ClothingHeadsetCargo
  innerclothingskirt: ClothingUniformJumpskirtCargo
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
