- type: job
  id: Quartermaster
  name: "quartermaster"
  startingGear: QuartermasterGear
  departments:
  - Cargo
  icon: "QuarterMaster"
  supervisors: "the head of personnel"
  access:
  - Cargo
  - Maintenance
  - External

- type: startingGear
  id: QuartermasterGear
  equipment:
    head: ClothingHeadHatCargosoft
    jumpsuit: ClothingUniformJumpsuitQM
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBrown
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
  innerclothingskirt: ClothingUniformJumpskirtQM
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
