- type: job
  id: Quartermaster
  name: job-name-qm
  playTimeTracker: JobQuartermaster
  startingGear: QuartermasterGear
  icon: "QuarterMaster"
  supervisors: job-supervisors-hop
  access:
  - Cargo
  - Maintenance
  - External

- type: startingGear
  id: QuartermasterGear
  equipment:
    head: ClothingHeadHatQMsoft
    jumpsuit: ClothingUniformJumpsuitQM
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBrown
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
  innerclothingskirt: ClothingUniformJumpskirtQM
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
