- type: job
  id: Paramedic
  name: job-name-paramedic
  description: job-description-paramedic
  startingGear: ParamedicGear
  playTimeTracker: JobParamedic
  icon: "Paramedic"
  supervisors: job-supervisors-cmo
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 14400
  access:
  - Medical
  - Maintenance
  - Service
  - External
  special:
  - !type:AddComponentSpecial
    components:
    - type: MedicalTraining

- type: startingGear
  id: ParamedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitParamedic
    back: ClothingBackpackParamedicFilled
    shoes: ClothingShoesColorWhite
    head: ClothingHeadHatParamedicsoft
    outerClothing: ClothingOuterCoatParamedicWB
    id: ParamedicPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    pocket1: HandheldGPSBasic
    pocket2: HandheldCrewMonitor
  innerclothingskirt: ClothingUniformJumpskirtParamedic
  satchel: ClothingBackpackSatchelParamedicFilled
  duffelbag: ClothingBackpackDuffelParamedicFilled
