- type: job
  id: Prisoner
  name: job-name-prisoner
  playTimeTracker: JobPrisoner
  startingGear: PrisonerGear
  alwaysUseSpawner: true
  canBeAntag: false
  icon: "Prisoner"
  supervisors: job-supervisors-security
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 3600

- type: startingGear
  id: PrisonerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisoner
    shoes: ClothingShoesColorBlack
    id: PrisonerPDA
    ears: ClothingHeadsetGrey
  innerclothingskirt: ClothingUniformJumpsuitPrisoner
