- type: job
  id: Passenger
  name: job-name-passenger
  description: job-description-assistant
  playTimeTracker: JobPassenger
  startingGear: PassengerGear
  icon: "Passenger"
  supervisors: job-supervisors-everyone
  extendedAccess:
  - Maintenance

- type: startingGear
  id: PassengerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  innerclothingskirt: ClothingUniformJumpskirtColorGrey
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
