- type: job
  id: Botanist
  name: "botanist"
  startingGear: BotanistGear
  departments:
  - Civilian
  icon: "Botanist"
  supervisors: "the head of personnel"
  access:
  - Service
  - Hydroponics
  extendedAccess:
  - Kitchen
  - Bar

- type: startingGear
  id: BotanistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHydroponics
    back: ClothingBackpackHydroponicsFilled
    shoes: ClothingShoesColorBrown
    id: BotanistPDA
    ears: ClothingHeadsetService
    outerClothing: ClothingOuterApronBotanist
    belt: ClothingBeltPlantFilled
  innerclothingskirt: ClothingUniformJumpskirtHydroponics
  satchel: ClothingBackpackSatchelHydroponicsFilled
  duffelbag: ClothingBackpackDuffelFilled
