- type: job
  id: Botanist
  name: job-name-botanist
  description: job-description-botanist
  playTimeTracker: JobBotanist
  startingGear: BotanistGear
  icon: "Botanist"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Hydroponics
  extendedAccess:
  - Kitchen
  - Bar
  - Maintenance

- type: startingGear
  id: BotanistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHydroponics
    back: ClothingBackpackHydroponicsFilled
    shoes: ClothingShoesColorBrown
    id: BotanistPDA
    ears: ClothingHeadsetService
    outerClothing: ClothingOuterApronBotanist
    belt: ClothingBeltPlantFilled
  innerclothingskirt: ClothingUniformJumpskirtHydroponics
  satchel: ClothingBackpackSatchelHydroponicsFilled
  duffelbag: ClothingBackpackDuffelHydroponicsFilled
