- type: job
  id: Clown
  name: "clown"
  startingGear: ClownGear
  departments:
  - Entertainment
  icon: "Clown"
  supervisors: "the head of personnel"
  access:
  - Theatre
  - Service
  special:
  - !type:AddComponentSpecial
    components:
    - type: Clumsy
      clumsyDamage:
        types: #literally just picked semi random valus. i tested this once and tweaked it.
          Blunt: 5
          Piercing: 4
        groups:
          Burn: 3

- type: startingGear
  id: ClownGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitClown
    back: ClothingBackpackClownFilled
    shoes: ClothingShoesClown
    mask: ClothingMaskClown
    pocket1: BikeHorn
    id: ClownPDA
    ears: ClothingHeadsetService
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelClownFilled
