- type: job
  id: Librarian
  name: "librarian"
  setPreference: false
  startingGear: LibrarianGear
  departments:
  - Civilian
  icon: "Librarian"
  supervisors: "the head of personnel"
  access:
  - Service
  - Maintenance

- type: startingGear
  id: LibrarianGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLibrarian
    back: ClothingBackpackBriefcaseFilled
    shoes: ClothingShoesColorBlack
    id: LibrarianPDA
    ears: ClothingHeadsetService
    pocket1: d10Dice
  innerclothingskirt: ClothingUniformJumpskirtColorLightBrown

