- type: job
  id: Reporter
  name: "reporter"
  startingGear: ReporterGear
  departments:
  - Civilian
  icon: "Reporter"
  supervisors: "the head of personnel"
  access:
  - Service
  - Maintenance

- type: startingGear
  id: ReporterGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitReporter
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorWhite
    id: ReporterPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpsuitJournalist
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
