- type: job
  id: ServiceWorker
  name: job-name-valet
  description: job-description-valet
  playTimeTracker: JobServiceWorker
  startingGear: ServiceWorkerGear
  icon: "ServiceWorker"
  supervisors: job-supervisors-everyone
  setPreference: false
  access:
  - Service
  - Bar
  - Kitchen
  - Cargo

- type: startingGear
  id: ServiceWorkerGear
  equipment:
    head: ClothingHeadHatBellhop
    jumpsuit: ClothingUniformJumpsuitBartender
    outerClothing: ClothingOuterVestValet
    gloves: ClothingHandsGlovesColorWhite
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: ServiceWorkerPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpskirtBartender
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
