- type: job
  id: ServiceWorker
  name: job-name-serviceworker
  playTimeTracker: JobServiceWorker
  startingGear: ServiceWorkerGear
  icon: "ServiceWorker"
  supervisors: job-supervisors-service
  canBeAntag: false
  access:
  - Service
  - Maintenance
  - Bar
  - Kitchen
  - Cargo

- type: startingGear
  id: ServiceWorkerGear
  equipment:
    head: ClothingHeadHatFez
    jumpsuit: ClothingUniformJumpsuitBartender
    outerClothing: ClothingOuterVestValet
    gloves: ClothingHandsGlovesColorWhite
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: ServiceWorkerPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpskirtBartender
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
