- type: job
  id: ResearchDirector
  name: "research director"
  setPreference: false
  weight: 10
  startingGear: ResearchDirectorGear
  departments:
  - Command
  - Science
  icon: "ResearchDirector"
  requireAdminNotify: true
  supervisors: "the captain"
  canBeAntag: false
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    back: ClothingBackpackScienceFilled
    shoes: ClothingShoesColorBrown
    outerClothing: ClothingOuterCoatLab
    id: RnDPDA
    ears: ClothingHeadsetScience
  innerclothingskirt: ClothingUniformJumpskirtResearchDirector
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled
