- type: latheRecipe
  id: ShockCollar
  icon:
    sprite: Nyanotrasen/Clothing/Neck/Misc/shock.rsi
    state: icon
  result: ShockCollar
  completetime: 2
  materials:
    Steel: 300
    Glass: 100
    Plastic: 100
