- type: latheRecipe
  id: ShockCollar
  icon:
    sprite: Nyanotrasen/Clothing/Neck/Misc/shock.rsi
    state: icon
  result: ShockCollar
  completetime: 2
  materials:
    Steel: 300
    Glass: 100
    Plastic: 100

- type: latheRecipe
  id: Decloner
  icon:
    sprite: Nyanotrasen/Objects/Weapons/Guns/Battery/decloner.rsi
    state: icon
  result: LockboxDecloner
  completetime: 4
  materials:
    Steel: 400
    Glass: 400
    Plastic: 400

- type: latheRecipe
  id: InsulativeHeadcage
  icon:
    sprite: Nyanotrasen/Clothing/Head/Hats/cage.rsi
    state: icon
  result: ClothingHeadCage
  completetime: 4
  materials:
    Steel: 400
    Bluespace: 20

- type: latheRecipe
  id: ShellSoulbreaker
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/shotgun_shell.rsi
    state: practice
  result: ShellSoulbreaker
  completetime: 4
  materials:
    Plastic: 15
    Steel: 10
    Bluespace: 10
    Glass: 5

- type: latheRecipe
  id: CartridgeSpecial
  result: CartridgeSpecial
  completetime: 2
  materials:
    Steel: 20

- type: latheRecipe
  id: CartridgeSpecialRubber
  result: CartridgeSpecialRubber
  completetime: 2
  materials:
    Plastic: 5
    Steel: 5

- type: latheRecipe
  id: CartridgeSpecialHoly
  result: CartridgeSpecialHoly
  completetime: 2
  materials:
    Plastic: 5
    Steel: 5
    Bluespace: 5
    Glass: 5

- type: latheRecipe
  id: MagazineBoxSpecial
  result: MagazineBoxSpecial
  completetime: 5
  materials:
    Steel: 1250

- type: latheRecipe
  id: MagazineBoxSpecialRubber
  result: MagazineBoxSpecialRubber
  completetime: 5
  materials:
    Steel: 350
    Plastic: 300